version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  reviewers:
  - snout-router/dependabot-reviewers
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
  reviewers:
  - snout-router/dependabot-reviewers
