const {expect} = require('chai')

const {resolveUrl} = require('../../src/url.js')

describe('resolveUrl()', function () {
  it('should support resolving against absolute URLs', function () {
    expect(resolveUrl('https://iconduit.github.io/', '.')).to.equal('https://iconduit.github.io/')
    expect(resolveUrl('https://iconduit.github.io/', '/')).to.equal('https://iconduit.github.io/')
    expect(resolveUrl('https://iconduit.github.io', '.')).to.equal('https://iconduit.github.io/')
    expect(resolveUrl('https://iconduit.github.io', '/')).to.equal('https://iconduit.github.io/')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', '/')).to.equal('https://iconduit.github.io/')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', 'x')).to.equal('https://iconduit.github.io/p/a/t/x')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h/', 'x')).to.equal('https://iconduit.github.io/p/a/t/h/x')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', 'x/')).to.equal('https://iconduit.github.io/p/a/t/x/')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', 'x/y')).to.equal('https://iconduit.github.io/p/a/t/x/y')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', 'x?y#z')).to.equal('https://iconduit.github.io/p/a/t/x?y#z')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', '.')).to.equal('https://iconduit.github.io/p/a/t/')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', './x')).to.equal('https://iconduit.github.io/p/a/t/x')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', '..')).to.equal('https://iconduit.github.io/p/a/')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', '../x')).to.equal('https://iconduit.github.io/p/a/x')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', '../../..')).to.equal('https://iconduit.github.io/')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', '../../../x')).to.equal('https://iconduit.github.io/x')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', '../../../..')).to.equal('https://iconduit.github.io/')
    expect(resolveUrl('https://iconduit.github.io/p/a/t/h', '../../../../x')).to.equal('https://iconduit.github.io/x')
  })

  it('should support resolving against relative URLs with a leading slash', function () {
    expect(resolveUrl('/', '')).to.equal('/')
    expect(resolveUrl('/', '.')).to.equal('/')
    expect(resolveUrl('/', '/')).to.equal('/')
    expect(resolveUrl('/', '/x/y')).to.equal('/x/y')
    expect(resolveUrl('/p/a/t/h', '')).to.equal('/p/a/t/h')
    expect(resolveUrl('/p/a/t/h', '/x/y')).to.equal('/x/y')
    expect(resolveUrl('/p/a/t/h', 'x')).to.equal('/p/a/t/x')
    expect(resolveUrl('/p/a/t/h/', 'x')).to.equal('/p/a/t/h/x')
    expect(resolveUrl('/p/a/t/h', 'x/')).to.equal('/p/a/t/x/')
    expect(resolveUrl('/p/a/t/h', 'x/y')).to.equal('/p/a/t/x/y')
    expect(resolveUrl('/p/a/t/h', 'x?y#z')).to.equal('/p/a/t/x?y#z')
    expect(resolveUrl('/p/a/t/h', '.')).to.equal('/p/a/t/')
    expect(resolveUrl('/p/a/t/h', './x')).to.equal('/p/a/t/x')
    expect(resolveUrl('/p/a/t/h', '..')).to.equal('/p/a/')
    expect(resolveUrl('/p/a/t/h', '../x')).to.equal('/p/a/x')
    expect(resolveUrl('/p/a/t/h', '../../..')).to.equal('/')
    expect(resolveUrl('/p/a/t/h', '../../../x')).to.equal('/x')
    expect(resolveUrl('/p/a/t/h', '../../../..')).to.equal('/')
    expect(resolveUrl('/p/a/t/h', '../../../../x')).to.equal('/x')
    expect(resolveUrl('/p/a/t/h', '../../../../..')).to.equal('/')
  })

  it('should support resolving against relative URLs without a leading slash', function () {
    expect(resolveUrl('', '')).to.equal('.')
    expect(resolveUrl('', '.')).to.equal('.')
    expect(resolveUrl('', '/')).to.equal('/')
    expect(resolveUrl('', '/x/y')).to.equal('/x/y')
    expect(resolveUrl('p/a/t/h', '')).to.equal('p/a/t/h')
    expect(resolveUrl('p/a/t/h', '/x/y')).to.equal('/x/y')
    expect(resolveUrl('p/a/t/h', 'x')).to.equal('p/a/t/x')
    expect(resolveUrl('p/a/t/h/', 'x')).to.equal('p/a/t/h/x')
    expect(resolveUrl('p/a/t/h', 'x/')).to.equal('p/a/t/x/')
    expect(resolveUrl('p/a/t/h', 'x/y')).to.equal('p/a/t/x/y')
    expect(resolveUrl('p/a/t/h', 'x?y#z')).to.equal('p/a/t/x?y#z')
    expect(resolveUrl('p/a/t/h', '.')).to.equal('p/a/t/')
    expect(resolveUrl('p/a/t/h', './x')).to.equal('p/a/t/x')
    expect(resolveUrl('p/a/t/h', '..')).to.equal('p/a/')
    expect(resolveUrl('p/a/t/h', '../x')).to.equal('p/a/x')
    expect(resolveUrl('p/a/t/h', '../../..')).to.equal('.')
    expect(resolveUrl('p/a/t/h', '../../../x')).to.equal('x')
    expect(resolveUrl('p/a/t/h', '../../../..')).to.equal('..')
    expect(resolveUrl('p/a/t/h', '../../../../x')).to.equal('../x')
    expect(resolveUrl('p/a/t/h', '../../../../..')).to.equal('../..')
  })
})
