module.exports = {
  'apple-touch-icon': {
    input: 'apple-touch-icon',
    name: 'apple-touch-icon-[dimensions].png',
    sizes: ['apple-touch-icon-retina'],
  },
  'apple-touch-startup': {
    input: 'apple-touch-startup',
    name: 'apple-touch-startup-[dimensions]r[pixelRatio].png',
    sizes: [
      'display.ipad-1536x2048d264.landscape',
      'display.ipad-1536x2048d264.portrait',
      'display.ipad-1536x2048d326.landscape',
      'display.ipad-1536x2048d326.portrait',
      'display.ipad-1668x2224d264.landscape',
      'display.ipad-1668x2224d264.portrait',
      'display.ipad-1668x2388d264.landscape',
      'display.ipad-1668x2388d264.portrait',
      'display.ipad-2048x2732d264.landscape',
      'display.ipad-2048x2732d264.portrait',
      'display.iphone-1125x2436.landscape',
      'display.iphone-1125x2436.portrait',
      'display.iphone-1242x2208.landscape',
      'display.iphone-1242x2208.portrait',
      'display.iphone-1242x2688.landscape',
      'display.iphone-1242x2688.portrait',
      'display.iphone-640x1136.landscape',
      'display.iphone-640x1136.portrait',
      'display.iphone-750x1334.landscape',
      'display.iphone-750x1334.portrait',
      'display.iphone-828x1792.landscape',
      'display.iphone-828x1792.portrait',
    ],
  },
  'browserconfig-xml': {
    input: 'browserconfig-xml',
    name: 'browserconfig.xml',
    sizes: [],
  },
  'dmg-background': {
    input: 'dmg-background',
    name: 'dmg-background[atPixelRatioX].png',
    sizes: ['dmg-background@2x', 'dmg-background'],
  },
  'facebook-app-icon': {
    input: 'facebook-app-icon',
    name: 'facebook-app-icon.png',
    sizes: ['facebook-app-icon'],
  },
  'favicon-ico': {
    input: 'masked-icon-minimal-padding',
    name: 'favicon.ico',
    sizes: ['favicon-large', 'favicon-medium', 'favicon-small'],
  },
  'favicon-png': {
    input: 'masked-icon-minimal-padding',
    name: 'favicon-[dimensions].png',
    sizes: ['favicon-medium', 'favicon-small'],
  },
  'index-html': {
    input: 'index-html',
    name: 'index.html',
    sizes: [],
  },
  'macos-icns': {
    input: 'macos-icon',
    name: 'macos.icns',
    sizes: [
      'icns-512@2x',
      'icns-512',
      'icns-256@2x',
      'icns-256',
      'icns-128@2x',
      'icns-128',
      'icns-64',
      'icns-32@2x',
      'icns-32',
      'icns-16@2x',
      'icns-16',
    ],
  },
  'manifest-json': {
    input: 'manifest-json',
    name: 'manifest.json',
    sizes: [],
  },
  'maskable-icon': {
    input: 'maskable-icon',
    name: 'maskable-icon-[dimensions].png',
    sizes: ['maskable-icon-hires', 'maskable-icon-lores'],
  },
  'open-graph-image': {
    input: 'open-graph-image',
    name: 'open-graph.png',
    sizes: ['open-graph-image'],
  },
  'safari-mask-icon': {
    input: 'safari-mask-icon',
    name: 'safari-mask-icon.svg',
    sizes: [],
  },
  'service-worker': {
    input: 'service-worker',
    name: 'service-worker.js',
    sizes: [],
  },
  'twitter-card-image': {
    input: 'twitter-card-image',
    name: 'twitter-card.png',
    sizes: ['twitter-card-image'],
  },
  'windows-ico': {
    input: 'masked-icon-minimal-padding',
    name: 'windows.ico',
    sizes: [
      'windows-ico-256',
      'windows-ico-128',
      'windows-ico-96',
      'windows-ico-64',
      'windows-ico-48',
      'windows-ico-40',
      'windows-ico-32',
      'windows-ico-24',
      'windows-ico-22',
      'windows-ico-16',
    ],
  },
  'windows-tile': {
    input: 'windows-tile',
    name: 'windows-tile-[dimensions].png',
    sizes: ['windows-tile-medium', 'windows-tile-large', 'windows-tile-wide'],
  },
  'windows-tile-small': {
    input: 'windows-tile-small',
    name: 'windows-tile-[dimensions].png',
    sizes: ['windows-tile-small'],
  },
}
