name: CI (scheduled)

on:
  schedule:
    - cron: 0 14 * * 0 # Sunday 2PM UTC = Monday 12AM AEST

jobs:
  ci:
    name: Iconduit
    uses: iconduit/repos/.github/workflows/shared-ci-library.yml@main
    secrets: inherit
    with:
      isScheduled: true
