name: CI
on:
  push:
  pull_request:
jobs:
  test:
    name: Node.js stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Check Node.js version
        run: node -v
      - name: Install dependencies
        run: make node_modules
      - name: Make
        run: make ci
      - name: Publish coverage
        uses: codecov/codecov-action@v1
