name: Publish release (manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to publish
        type: string
        required: true

jobs:
  publish:
    name: Iconduit
    uses: iconduit/repos/.github/workflows/shared-publish-release.yml@main
    secrets: inherit
    permissions:
      contents: write
      discussions: write
    with:
      tag: ${{ github.event.inputs.tag }}
