name: Publish package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Iconduit
    uses: iconduit/repos/.github/workflows/shared-publish-package.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
